version: "3.8"

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flights
    ports:
      - "5432:5432"

  api:
    image: ghcr.io/anthesk/flights-overhead:latest
    build: .
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/flights
    depends_on:
      - db

  worker:
    image: ghcr.io/anthesk/flights-overhead:latest
    build: .
    command: python3 -m app.worker
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/flights
    depends_on:
      - db

volumes:
  postgres_data:
